# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-toml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/myint/docformatter
  rev: v1.5.0
  hooks:
    - id: docformatter
      args:
        - --in-place
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.3.1'
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix]
- repo: https://github.com/jsh9/pydoclint
  rev: 0.4.1
  hooks:
    - id: pydoclint
      args:
        - --style=google
        - --arg-type-hints-in-docstring=false
        - --check-return-types=false
        - --check-yield-types=false
