name: code-style
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches: [main]
jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install and setup pre-commit
      run: pip install pre-commit && pre-commit install
    - name: Run pre-commit hooks on diff
      if: github.event_name == 'pull_request'
      run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} && pre-commit run --from-ref `git merge-base ${{ github.base_ref }} HEAD` --to-ref HEAD
    - name: Run pre-commit hooks on everything
      if: github.event_name == 'push'
      run: pre-commit run --all
